# -*- coding: utf-8 -*-
"""Heritage101_3_øvelse2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-_y8G-SJ0rmqLoAAFVar3okZaNaHmuow
"""

import requests
import pandas as pd
import numpy as np
from pandas.io.json import json_normalize

api_key = 'o7ejhb48ohglbckt'

api_search_url = 'https://api.trove.nla.gov.au/v2/result'

params = {
    'q': 'mahatma+gandhi',
    'zone': 'newspaper',
    'key': api_key,
    'facet': 'year',
    'encoding': 'json', 
    'n': 0 
}
response = requests.get(api_search_url, params=params)

print(response)

json = response.json()

df = json_normalize(json['response']['zone'][0]['facets']['facet']['term'])

df.head()

df.dtypes

df['count'] = pd.to_numeric(df['count'])

df.dtypes

to_drop = ['search', 'url']
df.drop(to_drop, inplace=True, axis=1)
df.head()

df.rename(columns={'display':'year'}, inplace=True)

df.head()



df.mean()

df.loc[:,"count"].mean()

df.median()

df.describe()

df

df.sort_index(axis=1)